---
title: 一个具有并发特性的异步任务调度工具
date: 2022-12-20 21:52
categories:
    - [javascripts]
---
## 需求
概述：存在 20 个异步任务等待执行，实现一个调度工具，满足同一时刻只能执行指定数量任务，并且在执行一个任务时，立马将执行任务达到上限，直到异步任务全部执行完毕。

[ ] 需要实现异步任务并发限制。
[ ] 当待执行任务池中存在任务时，同一时刻执行任务需要达到最大上限。

> 进阶：当任务失败时，进行 3 次重试，3 次重试后若还是失败，则中断所有异步任务

## 实现一：class 类 + async/await 模式
> 利用事件循环中，会首先清空微任务的原理，进行微任务“阻塞”，达到暂停执行的效果；

```typescript
class AsyncWorker {
   queue = []
   max = 0
   count = 0
  
  constructor( capacity) {
    this.max = capacity
    this.count = 0
    this.queue = []
  }

  async exec(task) {
    // show me the code, please delete the following line.
    if (this.count >= this.max) {
      await new Promise((resolve) => {
        this.queue.push(resolve)
      })
    }

    this.count++

    let res 
    
    // try catch 用来处理 reject 的情况
    try {
      res  = await task()
    } catch (e) {
      throw e
    } finally {
      this.count--
      if (this.queue.length) this.queue.shift()()
    }

    return res
  }
}
```
## 实现二：函数 + Promise 形式

```typescript
function AsyncWorker(this: any, max: number) {
  this.max = max
  this.count = 0
  this.queue = []
}

AsyncWorker.prototype.exec = function <T>(task: () => Promise<T>): Promise<T> {
  const run = (promise: () => Promise<T>) => {
    this.count++
    return promise().then((val) => {
      this.count--
      this.queue.length && this.queue.shift()()
      return val
    }).catch((err) => {
      this.count--
      this.queue.length && this.queue.shift()()
      throw err
    })
  }

  return new Promise<T>((resolve, reject) => {
    if (this.count < this.max) {
      run(task).then(resolve).catch(reject)
    } else {
      this.queue.push(() => {
        run(task).then(resolve).catch(reject)
      })
    }
  })
}
```
## 测试函数及用例
```typescript
async function testAsyncWorker() {
  const start = Date.now();
  const createTask = (timeout, error) => {
    return () =>
      new Promise((resolve, reject) => {
        setTimeout(() => {
          if (error) {
            reject(error);
          } else {
            resolve(timeout);
          }
        }, timeout);
      });
  };

  const worker = new AsyncWorker(2);


  const tasks = [
    { status: 'fulfilled', value: 100, idealCost: 100, task: worker.exec(createTask(100)) },
    { status: 'fulfilled', value: 201, idealCost: 200, task: worker.exec(createTask(201)) },
    // { status: 'fulfilled', value: 202, idealCost: 300, task: worker.exec(createTask(202)) },
    { status: 'rejected', reason: 'REJECTED', idealCost: 300, task: worker.exec(createTask(202, 'REJECTED')) },
    { status: 'fulfilled', value: 203, idealCost: 400, task: worker.exec(createTask(203)) },
    { status: 'fulfilled', value: 300, idealCost: 600, task: worker.exec(createTask(300)) },
  ];

  // show me bug does not support for of tasks.entries()
  for (let index = 0; index < tasks.length; index++) {
    const t = tasks[index];
    let result
    try {
      const value = await t.task;
      result = { status: 'fulfilled', value };
    } catch (e) {
      result = { status: 'rejected', reason: e };
    }
    
    const realCost = Date.now() - start;

    const idealCost = (realCost - (realCost % 100)) | 0;

    if (idealCost !== t.idealCost) {
      throw new Error(`unexpected time cost: ${idealCost}, expected is ${t.idealCost} for ${index}`);
    }
    if (result.status !== t.status) {
      throw new Error(`unexpected status ${result.status} for ${index}`);
    }
    if (t.status === 'fulfilled' && result.status === 'fulfilled' && result.value !== t.value) {
      throw new Error(`unexpected fulfilled value ${result.value}, expected is ${t.value} for ${index}`);
    }
    if (t.status === 'rejected' && result.status === 'rejected' && result.reason !== t.reason) {
      throw new Error(`unexpected rejected reason ${result.reason}, expected is ${t.reason} for ${index}`);
    }
  }
}
```
